package uam.fia.jaguarcare.model;

public enum Carrera {
    NOAPLICA,ADMEMPRESAS, ARQUITECTURA, COMUNICACION, DERECHO, DISENO, ECONOMIA, INGCIVIL, INGINDUSTRIAL, INGSISTEMAS, MARKETING, MEDICINA, NEGOCIOSINTERNACIONALES, ODONTOLOGIA, POSGRADO, PSICOLOGIA, RELACIONESINT, UAMCOLLEGE
}
