package uam.fia.jaguarcare.model;

public enum Carrera {
    NOAPLICA,POSGRADO,MEDICINA,ODONTOLOGIA,PSICOLOGIA,INGSISTEMAS,INGINDUSTRIAL,ARQUITECTURA,INGCIVIL,
    ECONOMIA,ADMEMPRESAS,NEGOCIOSINTERNACIONALES,MARKETING,DISENO,COMUNICACION,RELACIONESINT,DERECHO,UAMCOLLEGE
}
